server:
  servlet.context-path: /xxx
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/xxx?characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true
    username: xxx
    password: xxx
    tomcat:
      init-s-q-l: SET NAMES 'utf8mb4'
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jmx:
    default-domain: xxxtech
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

logging:
  file:
    name: /opt/javalog/xxx/test.log

